name:    lux
version: 0.1.0.0
github:  "zuqq/lux"
author:  "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- MonadRandom >= 0.5.2
- random >= 1.2.0

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  lux-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lux

tests:
  doctest:
    main:                Main.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - lux
