name:                lux
version:             0.1.0.0
github:              "zuqq/lux"
license:             BSD3
author:              "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/zuqq/lux#readme>

dependencies:
- base >= 4.7 && < 5
- MonadRandom
- streaming

library:
  source-dirs: src

executables:
  lux-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lux

tests:
  lux-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lux
