name:                lux
version:             0.1.0.0
github:              "zuqq/lux"
author:              "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/zuqq/lux#readme>

dependencies:
- base >= 4.7 && < 5
- MonadRandom

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  lux-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lux

tests:
  lux-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - lux
